"""Configuration for the two-scalar PSMI compatibility package."""

from __future__ import annotations

import os

import torch

from .paths import ABRAHAM_DATA, ABRAHAM_EXPERIMENT_ROOT, NRTL_PARAMETER_FILE


# Repository paths used by the binary-transfer helpers.
EXCEL_PATH = os.getenv("PSMI_COMPAT_EXCEL_PATH", str(ABRAHAM_DATA))
OUT_DIR = os.getenv("PSMI_COMPAT_OUT_DIR", str(ABRAHAM_EXPERIMENT_ROOT))
NRTL_PARAMS_PATH = str(NRTL_PARAMETER_FILE)
LOAD_CKPT_PATH = ""

# Reproducibility and data filtering.
SEED = 1007
MIN_POINTS_PER_GROUP = 1
PERMUTE_23_AUG = True
PRECOMPUTE_SCALARS = True
PRECOMPUTE_FEATURES = True
FP_RADIUS = 2
FP_BITS = 2048

# Molecular and mixture-graph settings used by the reference checkpoints.
USE_GRAPH = True
USE_MIX_GRAPH = True
MIX_HB_CUTOFF = 3.4
MIX_XB_CUTOFF = 3.6
MIX_PI_CUTOFF = 5.5
MIX_EDGE_MIN_CONTACTS = 1
MIX_ELEC_KEEP_THRESH = 0.05
MIX_PACKING_BUFFER = 0.8
MIX_LAYERS = 2
MIX_HIDDEN = 256
MIX_DROPOUT = 0.10
MIX_TRIPLE_CACHE_SIZE = 4096

GRAPH_ADD_HS = False
GRAPH_ADD_3D = False
GRAPH_USE_GASTEIGER = True
GRAPH_MAX_ATOMS = 256

# Checkpoint-compatible model dimensions.
HIDDEN = 1024
DROPOUT = 0.15
GNN_HIDDEN = 256
GNN_LAYERS = 4
GNN_POOL = "mean"
GNN_INTERACTION = True
GNN_HEAD_HIDDEN = 512

# Training defaults retained for reproducibility.
BATCH_SIZE = 1024
BATCH_SIZE_GRAPH = 128
EPOCHS = 50
LR = 1e-4
WEIGHT_DECAY = 1e-5
USE_AMP = True
GRAD_CLIP = 1.0
USE_MECH_LOSS = False
FREEZE_BACKBONE = False

LAMBDA_PHY = 1e-3
WARMUP_EPOCHS = 0
RAMP_EPOCHS = 5
ROBUST_DELTA = 5.0
TAU_CLIP = 10.0
LN_GAMMA_CLIP = 20.0
MECH_USE_KELVIN = None
MECH_W_EQ = 1.0
MECH_W_GD = 0.0
MECH_W_STAB = 0.0
MECH_GD_N_DIR = 2
MECH_GD_EPS = 1e-4
MECH_STAB_N_TRIAL = 64
MECH_STAB_SIGMA = 0.05
MECH_STAB_MARGIN = 0.05

EVAL_EVERY = 1
PLOT_EVERY = 5
USE_EARLY_STOP = False
EARLY_STOP_PATIENCE = 20
EARLY_STOP_METRIC = "mse"
EARLY_STOP_MIN_DELTA = 1e-5
USE_PHYSICS_FINETUNE = False
FINETUNE_EARLY_STOP_METRIC = "tpd_viol_rate"
FINETUNE_PATIENCE = 30

NUM_WORKERS = min(16, os.cpu_count() or 8)
NUM_WORKERS_GRAPH = 0
PREFETCH_FACTOR = 4
PRED_BATCH_SIZE_GRAPH = 128
N_SWEEP = 80
DRAW_TIELINES_MAX = 14

# Functional-group and feature-fusion settings required by best_model.pt.
USE_FG = True
FG_TOPK = 512
FG_MIN_FREQ = 3
FG_MLP_HIDDEN = 256
FG_DROPOUT = 0.10
PRECOMPUTE_FG = True
FG_TOKEN_MODE = True
FG_MAX_TOKENS = 32
FG_CROSS_ATTN = True
FG_ATTN_HEADS = 8
S3_EQUIVARIANT = True
FUSION_MODE = "tf"
TF_DIM = GNN_HIDDEN
TF_LAYERS = 2
TF_HEADS = 8
TF_FF = 1024
TF_DROPOUT = 0.15
TF_POOL = "cls"
TF_MAX_LEN = 32
TF_TYPE_VOCAB = 16

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
