EPOCHS: 30
LR: 0.000005
WEIGHT_DECAY: 0.001
BATCH_SIZE_GRAPH: 256
USE_MECH_LOSS: true
FREEZE_BACKBONE: true
USE_PHYSICS_FINETUNE: true
LAMBDA_PHY: 0.001
GE_MODEL: nrtl
MECH_W_EQ: 1.0
MECH_W_GD: 0.0
MECH_W_STAB: 0.0
USE_EARLY_STOP: true
FINETUNE_EARLY_STOP_METRIC: rmse
FINETUNE_PATIENCE: 30
GRAD_CLIP: 1.0
USE_AMP: true
EVALUATE_TEST_DURING_TRAINING: false
GENERATE_PHASE_DIAGRAMS: false
