EPOCHS: 300
LR: 0.00005
WEIGHT_DECAY: 0.001
BATCH_SIZE_GRAPH: 256
USE_MECH_LOSS: false
FREEZE_BACKBONE: false
USE_EARLY_STOP: true
EARLY_STOP_METRIC: rmse
EARLY_STOP_PATIENCE: 15
GRAD_CLIP: 1.0
USE_AMP: true
EVALUATE_TEST_DURING_TRAINING: false
GENERATE_PHASE_DIAGRAMS: false
